sudo: false
language: php
php:
  - 5.6
#  - 7.0
#  - 7.1

env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - MAGETESTSTAND_URL=https://github.com/ambimax/MageTestStand.git
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.3.4
    - MAGENTO_VERSION="magento-mirror-1.9.2.2"

script:
  - curl --retry 2 --retry-delay 5 -f -sSL https://raw.githubusercontent.com/ambimax/MageTestStand/master/setup.sh | bash
